python:
	wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
	bash Miniconda3-latest-Linux-x86_64.sh
conda_rm_bash:
	conda config --set auto_activate_base false
trash-cli:
	easy_install trash-cli
